import json
from argparse import ArgumentParser, FileType

from printer import Printer, print_tweet
from utils import Tweet


def main() -> None:
    parser = ArgumentParser(description="Prints tweet backlog to a line printer.")
    parser.add_argument(
        "archive", type=FileType(), help="Tweet backlog as generated by tweetquenz.py"
    )
    parser.add_argument(
        "--printer",
        default="/dev/lp0",
        help="Path to the printer device to use (default: /dev/lp0)",
        type=FileType("wb", bufsize=0),
    )
    parser.add_argument(
        "--encoding",
        default="cp437",
        help="Character set to use for the printer output (default: cp437)",
    )
    args = parser.parse_args()

    printer = Printer(args.printer, encoding=args.encoding)
    for line in args.archive:
        tweet = Tweet(**json.loads(line))
        print_tweet(tweet, printer)


if __name__ == "__main__":
    main()
